package modelo;
// Generated 9 abr. 2021 8:53:38 by Hibernate Tools 5.4.27.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Ciudades generated by hbm2java
 */
public class Ciudades implements java.io.Serializable {

	private int codigopostal;
	private String nombre;
	private Set salases = new HashSet(0);

	public Ciudades() {
	}

	public Ciudades(int codigopostal, String nombre) {
		this.codigopostal = codigopostal;
		this.nombre = nombre;
	}

	public Ciudades(int codigopostal, String nombre, Set salases) {
		this.codigopostal = codigopostal;
		this.nombre = nombre;
		this.salases = salases;
	}

	public int getCodigopostal() {
		return this.codigopostal;
	}

	public void setCodigopostal(int codigopostal) {
		this.codigopostal = codigopostal;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getSalases() {
		return this.salases;
	}

	public void setSalases(Set salases) {
		this.salases = salases;
	}

}
