package modelo;
// Generated 4 may. 2021 11:26:47 by Hibernate Tools 5.3.20.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Ciudades generated by hbm2java
 */
public class Ciudades implements java.io.Serializable {

	private Integer idciudad;
	private String nombreciudad;
	private String codigopostal;
	private Set ordens = new HashSet(0);

	public Ciudades() {
	}

	public Ciudades(String nombreciudad, String codigopostal) {
		this.nombreciudad = nombreciudad;
		this.codigopostal = codigopostal;
	}

	public Ciudades(String nombreciudad, String codigopostal, Set ordens) {
		this.nombreciudad = nombreciudad;
		this.codigopostal = codigopostal;
		this.ordens = ordens;
	}

	//Get y Set
	public Integer getIdciudad() {
		return this.idciudad;
	}

	public void setIdciudad(Integer idciudad) {
		this.idciudad = idciudad;
	}

	public String getNombreciudad() {
		return this.nombreciudad;
	}

	public void setNombreciudad(String nombreciudad) {
		this.nombreciudad = nombreciudad;
	}

	public String getCodigopostal() {
		return this.codigopostal;
	}

	public void setCodigopostal(String codigopostal) {
		this.codigopostal = codigopostal;
	}

	public Set getOrdens() {
		return this.ordens;
	}

	public void setOrdens(Set ordens) {
		this.ordens = ordens;
	}

}
