package modelo;
// Generated 4 may. 2021 11:26:47 by Hibernate Tools 5.3.20.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Clientes generated by hbm2java
 */
public class Clientes implements java.io.Serializable {

	private Integer idcliente;
	private String nombreCliente;
	private String nif;
	private Set ordens = new HashSet(0);

	public Clientes() {
	}

	public Clientes(String nombreCliente, String nif) {
		this.nombreCliente = nombreCliente;
		this.nif = nif;
	}

	public Clientes(String nombreCliente, String nif, Set ordens) {
		this.nombreCliente = nombreCliente;
		this.nif = nif;
		this.ordens = ordens;
	}

	//Get y Set
	public Integer getIdcliente() {
		return this.idcliente;
	}

	public void setIdcliente(Integer idcliente) {
		this.idcliente = idcliente;
	}

	public String getNombreCliente() {
		return this.nombreCliente;
	}

	public void setNombreCliente(String nombreCliente) {
		this.nombreCliente = nombreCliente;
	}

	public String getNif() {
		return this.nif;
	}

	public void setNif(String nif) {
		this.nif = nif;
	}

	public Set getOrdens() {
		return this.ordens;
	}

	public void setOrdens(Set ordens) {
		this.ordens = ordens;
	}

}
