package modelo;
// Generated 4 may. 2021 11:26:47 by Hibernate Tools 5.3.20.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Salas generated by hbm2java
 */
public class Salas implements java.io.Serializable {

	private Integer idsala;
	private String direccion;
	private String centro;
	private String nsala;
	private String nasistentes;
	private Set ordens = new HashSet(0);

	public Salas() {
	}

	public Salas(String direccion, String centro, String nsala, String nasistentes) {
		this.direccion = direccion;
		this.centro = centro;
		this.nsala = nsala;
		this.nasistentes = nasistentes;
	}

	public Salas(String direccion, String centro, String nsala, String nasistentes, Set ordens) {
		this.direccion = direccion;
		this.centro = centro;
		this.nsala = nsala;
		this.nasistentes = nasistentes;
		this.ordens = ordens;
	}

	//Get y Set 
	public Integer getIdsala() {
		return this.idsala;
	}

	public void setIdsala(Integer idsala) {
		this.idsala = idsala;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getCentro() {
		return this.centro;
	}

	public void setCentro(String centro) {
		this.centro = centro;
	}

	public String getNsala() {
		return this.nsala;
	}

	public void setNsala(String nsala) {
		this.nsala = nsala;
	}

	public String getNasistentes() {
		return this.nasistentes;
	}

	public void setNasistentes(String nasistentes) {
		this.nasistentes = nasistentes;
	}

	public Set getOrdens() {
		return this.ordens;
	}

	public void setOrdens(Set ordens) {
		this.ordens = ordens;
	}

}
